"""second

Revision ID: 076e4e261e29
Revises: 91fde95bf761
Create Date: 2026-04-06 21:55:37.514497

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "076e4e261e29"
down_revision: str | Sequence[str] | None = "91fde95bf761"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###
