"""third

Revision ID: 38fe99d1d531
Revises: 076e4e261e29
Create Date: 2026-04-06 22:01:21.359231

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "38fe99d1d531"
down_revision: str | Sequence[str] | None = "076e4e261e29"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		"refresh_tokens",
		"expires_at",
		existing_type=postgresql.TIMESTAMP(),
		type_=sa.DateTime(timezone=True),
		existing_nullable=False,
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		"refresh_tokens",
		"expires_at",
		existing_type=sa.DateTime(timezone=True),
		type_=postgresql.TIMESTAMP(),
		existing_nullable=False,
	)
	# ### end Alembic commands ###
