"""initial

Revision ID: 91fde95bf761
Revises:
Create Date: 2026-04-06 21:52:16.936050

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91fde95bf761"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"categories",
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("slug", sa.String(length=255), nullable=False),
		sa.Column("description", sa.Text(), nullable=True),
		sa.Column("icon", sa.String(length=255), nullable=True),
		sa.Column("pk_id", sa.Integer(), nullable=False),
		sa.Column("id", sa.Uuid(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("pk_id"),
	)
	op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=True)
	op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=True)
	op.create_table(
		"countries",
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("code", sa.String(length=3), nullable=False),
		sa.Column("pk_id", sa.Integer(), nullable=False),
		sa.Column("id", sa.Uuid(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("pk_id"),
	)
	op.create_index(op.f("ix_countries_code"), "countries", ["code"], unique=True)
	op.create_index(op.f("ix_countries_id"), "countries", ["id"], unique=True)
	op.create_table(
		"users",
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("email", sa.String(length=255), nullable=False),
		sa.Column("password_hash", sa.String(length=255), nullable=False),
		sa.Column("profile_image_url", sa.String(length=500), nullable=True),
		sa.Column(
			"role",
			sa.Enum("REVIEWER", "REVIEWED", "ADMIN", name="userroleenum"),
			nullable=False,
		),
		sa.Column("is_verified", sa.Boolean(), nullable=False),
		sa.Column("pk_id", sa.Integer(), nullable=False),
		sa.Column("id", sa.Uuid(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("pk_id"),
	)
	op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
	op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
	op.create_table(
		"refresh_tokens",
		sa.Column("user_pk_id", sa.Integer(), nullable=False),
		sa.Column("token", sa.String(length=512), nullable=False),
		sa.Column("expires_at", sa.DateTime(), nullable=False),
		sa.Column("revoked", sa.Boolean(), nullable=False),
		sa.Column("pk_id", sa.Integer(), nullable=False),
		sa.Column("id", sa.Uuid(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["user_pk_id"],
			["users.pk_id"],
		),
		sa.PrimaryKeyConstraint("pk_id"),
	)
	op.create_index(op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=True)
	op.create_index(
		op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=True
	)
	op.create_table(
		"states",
		sa.Column("country_pk_id", sa.Integer(), nullable=False),
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("pk_id", sa.Integer(), nullable=False),
		sa.Column("id", sa.Uuid(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["country_pk_id"],
			["countries.pk_id"],
		),
		sa.PrimaryKeyConstraint("pk_id"),
	)
	op.create_index(op.f("ix_states_id"), "states", ["id"], unique=True)
	op.create_table(
		"cities",
		sa.Column("state_pk_id", sa.Integer(), nullable=False),
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("pk_id", sa.Integer(), nullable=False),
		sa.Column("id", sa.Uuid(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["state_pk_id"],
			["states.pk_id"],
		),
		sa.PrimaryKeyConstraint("pk_id"),
	)
	op.create_index(op.f("ix_cities_id"), "cities", ["id"], unique=True)
	op.create_table(
		"reviewed_entities",
		sa.Column("city_pk_id", sa.Integer(), nullable=False),
		sa.Column("category_pk_id", sa.Integer(), nullable=False),
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("description", sa.Text(), nullable=True),
		sa.Column("image_url", sa.String(length=500), nullable=True),
		sa.Column("role_title", sa.String(length=255), nullable=True),
		sa.Column(
			"status",
			sa.Enum("PENDING", "APPROVED", "REJECTED", name="statusenum"),
			nullable=False,
		),
		sa.Column("approved_by_pk_id", sa.Integer(), nullable=True),
		sa.Column("approved_at", sa.DateTime(), nullable=True),
		sa.Column("pk_id", sa.Integer(), nullable=False),
		sa.Column("id", sa.Uuid(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["approved_by_pk_id"],
			["users.pk_id"],
		),
		sa.ForeignKeyConstraint(
			["category_pk_id"],
			["categories.pk_id"],
		),
		sa.ForeignKeyConstraint(
			["city_pk_id"],
			["cities.pk_id"],
		),
		sa.PrimaryKeyConstraint("pk_id"),
	)
	op.create_index(
		op.f("ix_reviewed_entities_id"), "reviewed_entities", ["id"], unique=True
	)
	op.create_table(
		"suggestions",
		sa.Column("user_pk_id", sa.Integer(), nullable=False),
		sa.Column("city_pk_id", sa.Integer(), nullable=False),
		sa.Column("category_pk_id", sa.Integer(), nullable=False),
		sa.Column("suggested_name", sa.String(length=255), nullable=False),
		sa.Column("description", sa.Text(), nullable=True),
		sa.Column("source_url", sa.String(length=500), nullable=True),
		sa.Column(
			"status",
			sa.Enum("PENDING", "APPROVED", "REJECTED", name="statusenum"),
			nullable=False,
		),
		sa.Column("reviewed_by_pk_id", sa.Integer(), nullable=True),
		sa.Column("reviewed_at", sa.DateTime(), nullable=True),
		sa.Column("pk_id", sa.Integer(), nullable=False),
		sa.Column("id", sa.Uuid(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["category_pk_id"],
			["categories.pk_id"],
		),
		sa.ForeignKeyConstraint(
			["city_pk_id"],
			["cities.pk_id"],
		),
		sa.ForeignKeyConstraint(
			["reviewed_by_pk_id"],
			["users.pk_id"],
		),
		sa.ForeignKeyConstraint(
			["user_pk_id"],
			["users.pk_id"],
		),
		sa.PrimaryKeyConstraint("pk_id"),
	)
	op.create_index(op.f("ix_suggestions_id"), "suggestions", ["id"], unique=True)
	op.create_table(
		"reviews",
		sa.Column("reviewed_entity_pk_id", sa.Integer(), nullable=False),
		sa.Column("user_pk_id", sa.Integer(), nullable=False),
		sa.Column("rating", sa.Integer(), nullable=False),
		sa.Column("comment", sa.Text(), nullable=True),
		sa.Column("pk_id", sa.Integer(), nullable=False),
		sa.Column("id", sa.Uuid(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["reviewed_entity_pk_id"],
			["reviewed_entities.pk_id"],
		),
		sa.ForeignKeyConstraint(
			["user_pk_id"],
			["users.pk_id"],
		),
		sa.PrimaryKeyConstraint("pk_id"),
	)
	op.create_index(op.f("ix_reviews_id"), "reviews", ["id"], unique=True)
	op.create_table(
		"user_reviewed_entities",
		sa.Column("user_pk_id", sa.Integer(), nullable=False),
		sa.Column("reviewed_entity_pk_id", sa.Integer(), nullable=False),
		sa.Column("pk_id", sa.Integer(), nullable=False),
		sa.Column("id", sa.Uuid(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["reviewed_entity_pk_id"],
			["reviewed_entities.pk_id"],
		),
		sa.ForeignKeyConstraint(
			["user_pk_id"],
			["users.pk_id"],
		),
		sa.PrimaryKeyConstraint("pk_id"),
	)
	op.create_index(
		op.f("ix_user_reviewed_entities_id"),
		"user_reviewed_entities",
		["id"],
		unique=True,
	)
	op.create_table(
		"review_responses",
		sa.Column("review_pk_id", sa.Integer(), nullable=False),
		sa.Column("user_reviewed_entity_pk_id", sa.Integer(), nullable=False),
		sa.Column("content", sa.Text(), nullable=False),
		sa.Column("pk_id", sa.Integer(), nullable=False),
		sa.Column("id", sa.Uuid(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["review_pk_id"],
			["reviews.pk_id"],
		),
		sa.ForeignKeyConstraint(
			["user_reviewed_entity_pk_id"],
			["user_reviewed_entities.pk_id"],
		),
		sa.PrimaryKeyConstraint("pk_id"),
	)
	op.create_index(
		op.f("ix_review_responses_id"), "review_responses", ["id"], unique=True
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_index(op.f("ix_review_responses_id"), table_name="review_responses")
	op.drop_table("review_responses")
	op.drop_index(
		op.f("ix_user_reviewed_entities_id"), table_name="user_reviewed_entities"
	)
	op.drop_table("user_reviewed_entities")
	op.drop_index(op.f("ix_reviews_id"), table_name="reviews")
	op.drop_table("reviews")
	op.drop_index(op.f("ix_suggestions_id"), table_name="suggestions")
	op.drop_table("suggestions")
	op.drop_index(op.f("ix_reviewed_entities_id"), table_name="reviewed_entities")
	op.drop_table("reviewed_entities")
	op.drop_index(op.f("ix_cities_id"), table_name="cities")
	op.drop_table("cities")
	op.drop_index(op.f("ix_states_id"), table_name="states")
	op.drop_table("states")
	op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
	op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
	op.drop_table("refresh_tokens")
	op.drop_index(op.f("ix_users_id"), table_name="users")
	op.drop_index(op.f("ix_users_email"), table_name="users")
	op.drop_table("users")
	op.drop_index(op.f("ix_countries_id"), table_name="countries")
	op.drop_index(op.f("ix_countries_code"), table_name="countries")
	op.drop_table("countries")
	op.drop_index(op.f("ix_categories_slug"), table_name="categories")
	op.drop_index(op.f("ix_categories_id"), table_name="categories")
	op.drop_table("categories")
	# ### end Alembic commands ###
